# Generated by Django 3.2.8 on 2021-10-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20211018_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(related_name='casting', to='jobs.Skill'),
        ),
    ]
